/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classifier;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali Haidar
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    ArrayList<Set> trainings;
    ArrayList<Set> tests;
    DataBaseHandler db;
    Methods methods;
    public Interface() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void init()
    {
        db=new DataBaseHandler();
        trainings=db.getAthletesTraining();
        tests =db.getAthletesTest();
        methods=new Methods();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_sets = new javax.swing.JComboBox<>();
        btn_distance = new javax.swing.JButton();
        btn_bayes = new javax.swing.JButton();
        btn_knn = new javax.swing.JButton();
        btn_normalization = new javax.swing.JButton();
        btn_mss = new javax.swing.JButton();
        label_accuracy = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_weight = new javax.swing.JTextField();
        text_height = new javax.swing.JTextField();
        btn_find_athletes = new javax.swing.JButton();
        label_athletes = new javax.swing.JLabel();
        combo_athletes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_num1 = new javax.swing.JTextField();
        text_num2 = new javax.swing.JTextField();
        text_num3 = new javax.swing.JTextField();
        text_num4 = new javax.swing.JTextField();
        btn_find_iris = new javax.swing.JButton();
        label_iris = new javax.swing.JLabel();
        combo_iris = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo_sets.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_sets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Athletes", "Iris", "Cancer" }));
        combo_sets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_setsActionPerformed(evt);
            }
        });

        btn_distance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_distance.setText("Distance");
        btn_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distanceActionPerformed(evt);
            }
        });

        btn_bayes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_bayes.setText("Bayes");
        btn_bayes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayesActionPerformed(evt);
            }
        });

        btn_knn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_knn.setText("KNN");
        btn_knn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_knnActionPerformed(evt);
            }
        });

        btn_normalization.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_normalization.setText("Normalization");
        btn_normalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalizationActionPerformed(evt);
            }
        });

        btn_mss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_mss.setText("MSS");
        btn_mss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mssActionPerformed(evt);
            }
        });

        label_accuracy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Weight:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Height:");

        text_weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_find_athletes.setText("Find");
        btn_find_athletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_athletesActionPerformed(evt);
            }
        });

        label_athletes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        combo_athletes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distance", "Norm", "MSS", "KNN", "Bayes" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_find_athletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_height))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(label_athletes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(combo_athletes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_athletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_athletes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_find_athletes)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Athletes", jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("num1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("num2:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("num3:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("num4:");

        btn_find_iris.setText("Find");
        btn_find_iris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_irisActionPerformed(evt);
            }
        });

        label_iris.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        combo_iris.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distance", "Norm", "MSS", "KNN", "Bayes" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(combo_iris, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_find_iris, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_num4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(137, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_num3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_iris)
                        .addGap(165, 165, 165))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_iris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_iris))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_find_iris)
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("Iris", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(combo_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_normalization)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_mss, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_knn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_bayes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(label_accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mss, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_normalization, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_knn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bayes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(label_accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distanceActionPerformed
        double counter=0;
        for(Set test:tests)
        {
            if(methods.distance(test, trainings).equals(test.getClas().trim()))
                counter++;
        }
        double res=(counter/tests.size())*100;
        label_accuracy.setText("accuracy:"+res+" %");
        
    }//GEN-LAST:event_btn_distanceActionPerformed

    private void btn_bayesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayesActionPerformed
        
        // TODO add your handling code here:
        double counter=0;
        for(Set test:tests)
        {
            if(methods.Bayes(test, trainings).equals(test.getClas().trim()))
                counter++;
        }
        double res=(counter/tests.size())*100;
        label_accuracy.setText("accuracy:"+res+" %");
    }//GEN-LAST:event_btn_bayesActionPerformed

    private void btn_knnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_knnActionPerformed
        // TODO add your handling code here:
        int k=Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the value of k:"));
        double counter=0;
        for(Set test:tests)
        {
            if(methods.KNN(test, trainings,k).equals(test.getClas().trim()))
                counter++;
        }
        double res=(counter/tests.size())*100;
        label_accuracy.setText("accuracy:"+res+" %");
    }//GEN-LAST:event_btn_knnActionPerformed

    private void btn_normalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalizationActionPerformed
        double counter=0;
        for(Set test:tests)
        {
            if(methods.Normalization(test, trainings).equals(test.getClas().trim()))
                counter++;
        }
        double res=(counter/tests.size())*100;
        label_accuracy.setText("accuracy:"+res+" %");
    }//GEN-LAST:event_btn_normalizationActionPerformed

    private void btn_mssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mssActionPerformed
        double counter=0;
        for(Set test:tests)
        {
            if(methods.MSS(test, trainings).equals(test.getClas().trim()))
                counter++;
        }
        double res=(counter/tests.size())*100;
        label_accuracy.setText("accuracy:"+res+" %");
    }//GEN-LAST:event_btn_mssActionPerformed

    private void combo_setsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_setsActionPerformed
        String selected=(String)combo_sets.getSelectedItem();
        switch(selected)
        {
            case "Athletes" :
            {
                trainings=db.getAthletesTraining();
                tests=db.getAthletesTest();
                break;
            }
            case "Iris" :
            {
                trainings=db.getIrisTrainings();
                tests=db.getIrisTest();
                break;
            }
            case "Cancer" :
            {
                trainings=db.getCancerTrainings();
                tests=db.getCancerTest();
                break;
            }
        }
    }//GEN-LAST:event_combo_setsActionPerformed

    private void btn_find_athletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_athletesActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Double> attrs=new ArrayList<>();
        attrs.add(Double.parseDouble(text_height.getText()));
        attrs.add(Double.parseDouble(text_weight.getText()));
        Set set=new Set(attrs);
        String rs="";
        String selected=(String)combo_athletes.getSelectedItem();
        switch(selected)
        {
            case "Distance" :
            {
                rs=methods.distance(set, db.getAthletesTraining());
                break;
            }
            case "Norm" :
            {
                rs=methods.Normalization(set, db.getAthletesTraining());
                break;
            }
            case "MSS" :
            {
                rs=methods.MSS(set, db.getAthletesTraining());
                break;
            }
            case "KNN" :
            {
                rs=methods.KNN(set, db.getAthletesTraining(),3);
                break;
            }
            case "Bayes" :
            {
                rs=methods.Bayes(set, db.getAthletesTraining());
                break;
            }
        }
        label_athletes.setText(rs);
    }//GEN-LAST:event_btn_find_athletesActionPerformed

    private void btn_find_irisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_irisActionPerformed
        
        ArrayList<Double> attrs=new ArrayList<>();
        attrs.add(Double.parseDouble(text_num1.getText()));
        attrs.add(Double.parseDouble(text_num2.getText()));
        attrs.add(Double.parseDouble(text_num3.getText()));
        attrs.add(Double.parseDouble(text_num4.getText()));
        Set set=new Set(attrs);
        String rs="";
        String selected=(String)combo_iris.getSelectedItem();
        switch(selected)
        {
            case "Distance" :
            {
                rs=methods.distance(set, db.getIrisTrainings());
                break;
            }
            case "Norm" :
            {
                rs=methods.Normalization(set, db.getIrisTrainings());
                break;
            }
            case "MSS" :
            {
                rs=methods.MSS(set, db.getIrisTrainings());
                break;
            }
            case "KNN" :
            {
                rs=methods.KNN(set, db.getIrisTrainings(),3);
                break;
            }
            case "Bayes" :
            {
                rs=methods.Bayes(set, db.getIrisTrainings());
                break;
            }
        }
        label_iris.setText(rs);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_find_irisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayes;
    private javax.swing.JButton btn_distance;
    private javax.swing.JButton btn_find_athletes;
    private javax.swing.JButton btn_find_iris;
    private javax.swing.JButton btn_knn;
    private javax.swing.JButton btn_mss;
    private javax.swing.JButton btn_normalization;
    private javax.swing.JComboBox<String> combo_athletes;
    private javax.swing.JComboBox<String> combo_iris;
    private javax.swing.JComboBox<String> combo_sets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_accuracy;
    private javax.swing.JLabel label_athletes;
    private javax.swing.JLabel label_iris;
    private javax.swing.JTextField text_height;
    private javax.swing.JTextField text_num1;
    private javax.swing.JTextField text_num2;
    private javax.swing.JTextField text_num3;
    private javax.swing.JTextField text_num4;
    private javax.swing.JTextField text_weight;
    // End of variables declaration//GEN-END:variables
}
